---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcbot-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcbot
  template:
    metadata:
      labels:
        app: dcbot
    spec:
      containers:
        - name: dcbot
          image: ghcr.io/eusdenlin/dc-bot:latest
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
        